version: "3.7"

networks:
  dev:
    driver: bridge
  gnotify-network:
    driver: bridge

services:
  authentication:
    image: authentication:latest
    ports:
      - "5000:80"
    networks:
      - dev
      - gnotify-network

  notification:
    image: notification:latest
    ports:
      - "5001:80"
    networks:
      - dev
      - gnotify-network

  vehicle:
    image: vehicle:latest
    ports:
      - "5002:80"
    networks:
      - dev
      - gnotify-network

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - dev

volumes:
  mongodb_data_container:
