version: "3.7"
networks:
  dev:
    driver: bridge

services:
  # server:
  #   image: docker.io/library/auth-image
  #   depends_on:
  #     - mongodb_container
  #   container_name: "gnotify-service"
  #   ports:
  #     - "8081:80"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   networks:
  #     - dev

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - dev

volumes:
  mongodb_data_container:
