version: "3.7"
networks:
  dev:
    driver: bridge

services:
  # goma-vehicle:
  #   image: docker.io/library/goma-vehicle
  #   depends_on:
  #     - mongodb_container
  #   container_name: "gnotify-vehicle"
  #   ports:
  #     - "8001:8003"
  #   build:
  #     context: .
  #     dockerfile: ./gNotifyVehicleService/Dockerfile
  #   networks:
  #     - dev

  # goma-auth:
  #   image: docker.io/library/goma-auth
  #   depends_on:
  #     - mongodb_container
  #   container_name: "gnotify-auth"
  #   ports:
  #     - "8000:8002"
  #   build:
  #     context: .
  #     dockerfile: ./gNotifyAuthenticationService/Dockerfile
  #   networks:
  #     - dev

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - dev

volumes:
  mongodb_data_container:
