gt:
	git add . && git commit -m '${comment}' && git push origin main
exec:
	docker exec -it ${id} bash 
down:
	docker compose down
up:
	docker compose up -d
build:
	dotnet build
run:
	dotnet watch run